name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=AKIAQ3EGSDAPQEKMT34Q" >> ~/.aws/credentials
          echo "aws_secret_access_key=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" >> ~/.aws/credentials
          echo "[default]" > ~/.aws/config
          echo "region=us-east-1" >> ~/.aws/config

      - name: Build Docker image
        run: |
          docker build -t entrevista-devops .

      - name: Login to Amazon ECR
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/b5v3l6v9

      - name: Tag Docker image
        run: |
          docker tag entrevista-devops:latest public.ecr.aws/b5v3l6v9/entrevista-devops:latest

      - name: Push Docker image to ECR
        run: |
          docker push public.ecr.aws/b5v3l6v9/entrevista-devops:latest
